Compile fixes:
* error: ‘remove_cv_t’ is not a member of ‘std’; did you mean
  ‘remove_cv’ fixed with switching to std:c++17 standard.

* added ISO C++ 19.1 exception class <stdexcept> to support latest
  g++ on modern Linux distributions.